### ISSUE TITLE
GitHub-link install

### ISSUE THREAD

**Issue by pedro-mendonca** [szepeviktor/wordpress-plugin-construction#3]
How is this installed?
https://github.com/szepeviktor/wordpress-plugin-construction/tree/master/github-link

**Comment by szepeviktor** [comment]
I am messy:
https://github.com/szepeviktor/github-link

**Comment by szepeviktor** [comment]
Use GHU's installer.

**Comment by pedro-mendonca** [comment]
Thanks, all working now :+1:
