### ISSUE TITLE
Missing apple-app-site-association

### ISSUE THREAD

**Issue by leeclemens** [szepeviktor/wordpress-plugin-construction#4]
Seems /apple-app-site-association may be missing? Apparently automatically requested by Safari for authenticated sites/apps

**Comment by szepeviktor** [comment]
Thank you!
Added to the list:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/shared-hosting-aid/README.md#root-files

**Comment by szepeviktor** [comment]
This repos is kind of a backup of all my notes and code related to WP until they evolve to be moved to a separate repo. (Then added as a submodule here, as [you can see](https://github.com/szepeviktor/wordpress-plugin-construction)).
